version: '3.3'
services:
  service1:
    image: busybox:latest
    command: date
    deploy:
      replicas: 0
      restart_policy:
        condition: none

# docker service create --name bbls --restart-condition none --replicas 0 busybox date
