version: '3.3'
services:
  manager:
    image: rayyanqcri/swarm-scheduler
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_URL=unix:///var/run/docker.sock
    configs:
      - crontab
    deploy:
      placement:
        constraints:
          - node.role == manager
configs:
  crontab:
    external: true

